name: grpc_analysis_server
description: The Dart analysis server on Cloud Run via gRPC.
version: 0.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  async: ^2.8.1
  grpc: ^3.0.0
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
